version: "3.8"
services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
    command:
      - spark-submit
      - --master
      - local[*]
      - etl/etl.py
      - --config
      - config/config.yaml
    volumes:
      - ./:/app
    working_dir: /app

  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: sales
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
