# Dockerfile.spark
FROM bitnami/spark:latest

USER root

# Copy requirements and install Python deps
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

USER 1001
