version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: "[%(asctime)s] %(levelname)s %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO

loggers:
  etl:
    handlers: [console]
    level: INFO
    propagate: false
  api:
    handlers: [console]
    level: INFO
    propagate: false

root:
  handlers: [console]
  level: WARNING
